In [1]:
import pandas as pd

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier,plot_tree
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.preprocessing import  MinMaxScaler, StandardScaler

In [2]:
df=pd.read_csv('glass.csv')

In [3]:
df

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]

In [4]:
df.dtypes

RI      float64
Na      float64
Mg      float64
Al      float64
Si      float64
K       float64
Ca      float64
Ba      float64
Fe      float64
Type      int64
dtype: object

In [5]:
df.shape

(214, 10)

In [6]:
df.isnull()

        RI     Na     Mg     Al     Si      K     Ca     Ba     Fe   Type
0    False  False  False  False  False  False  False  False  False  False
1    False  False  False  False  False  False  False  False  False  False
2    False  False  False  False  False  False  False  False  False  False
3    False  False  False  False  False  False  False  False  False  False
4    False  False  False  False  False  False  False  False  False  False
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
209  False  False  False  False  False  False  False  False  False  False
210  False  False  False  False  False  False  False  False  False  False
211  False  False  False  False  False  False  False  False  False  False
212  False  False  False  False  False  False  False  False  False  False
213  False  False  False  False  False  False  False  False  False  False

[214 rows x 10 columns]

In [7]:
df.isnull().sum()

RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64

In [8]:
(df==0).sum()

RI        0
Na        0
Mg       42
Al        0
Si        0
K        30
Ca        0
Ba      176
Fe      144
Type      0
dtype: int64

In [9]:
df.mean()

RI       1.518365
Na      13.407850
Mg       2.684533
Al       1.444907
Si      72.650935
K        0.497056
Ca       8.956963
Ba       0.175047
Fe       0.057009
Type     2.780374
dtype: float64

In [10]:
df.median()

RI       1.51768
Na      13.30000
Mg       3.48000
Al       1.36000
Si      72.79000
K        0.55500
Ca       8.60000
Ba       0.00000
Fe       0.00000
Type     2.00000
dtype: float64

In [11]:
df.mode()

        RI     Na   Mg    Al     Si    K    Ca   Ba   Fe  Type
0  1.51590  13.00  0.0  1.54  72.86  0.0  8.03  0.0  0.0   2.0
1  1.51645  13.02  NaN   NaN  72.99  NaN  8.43  NaN  NaN   NaN
2  1.52152  13.21  NaN   NaN  73.10  NaN   NaN  NaN  NaN   NaN
3      NaN    NaN  NaN   NaN  73.11  NaN   NaN  NaN  NaN   NaN
4      NaN    NaN  NaN   NaN  73.28  NaN   NaN  NaN  NaN   NaN

In [12]:
"""df=(df-df.min())/(df.max()-df.min())  #Normalization-Using Formula
df"""

'df=(df-df.min())/(df.max()-df.min())  #Normalization-Using Formula\ndf'

In [13]:
df1=df[['RI','Na','Mg','Al','Si','K','Ca','Ba','Fe']]

In [14]:
df1=pd.DataFrame(MinMaxScaler().fit_transform(df1),columns=df1.columns)
df1

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe
0,0.432836,0.437594,1.000000,0.252336,0.351786,0.009662,0.308550,0.000000,0.0
1,0.283582,0.475188,0.801782,0.333333,0.521429,0.077295,0.223048,0.000000,0.0
2,0.220808,0.421053,0.790646,0.389408,0.567857,0.062802,0.218401,0.000000,0.0
3,0.285777,0.372932,0.821826,0.311526,0.500000,0.091787,0.259294,0.000000,0.0
4,0.275241,0.381955,0.806236,0.295950,0.583929,0.088567,0.245353,0.000000,0.0
...,...,...,...,...,...,...,...,...,...
209,0.223003,0.512782,0.000000,0.806854,0.500000,0.012882,0.348513,0.336508,0.0
210,0.250219,0.630075,0.000000,0.529595,0.580357,0.000000,0.276022,0.504762,0.0
211,0.417032,0.545865,0.000000,0.538941,0.644643,0.000000,0.279740,0.520635,0.0
212,0.235294,0.548872,0.000000,0.514019,0.678571,0.000000,0.283457,0.498413,0.0
213,0.261633,0.526316,0.000000,0.557632,0.633929,0.000000,0.296468,0.530159,0.0

In [15]:
x=df1[['RI','Na','Mg','Al','Si','K','Ca','Ba','Fe']]

In [16]:
x

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe
0,0.432836,0.437594,1.000000,0.252336,0.351786,0.009662,0.308550,0.000000,0.0
1,0.283582,0.475188,0.801782,0.333333,0.521429,0.077295,0.223048,0.000000,0.0
2,0.220808,0.421053,0.790646,0.389408,0.567857,0.062802,0.218401,0.000000,0.0
3,0.285777,0.372932,0.821826,0.311526,0.500000,0.091787,0.259294,0.000000,0.0
4,0.275241,0.381955,0.806236,0.295950,0.583929,0.088567,0.245353,0.000000,0.0
...,...,...,...,...,...,...,...,...,...
209,0.223003,0.512782,0.000000,0.806854,0.500000,0.012882,0.348513,0.336508,0.0
210,0.250219,0.630075,0.000000,0.529595,0.580357,0.000000,0.276022,0.504762,0.0
211,0.417032,0.545865,0.000000,0.538941,0.644643,0.000000,0.279740,0.520635,0.0
212,0.235294,0.548872,0.000000,0.514019,0.678571,0.000000,0.283457,0.498413,0.0
213,0.261633,0.526316,0.000000,0.557632,0.633929,0.000000,0.296468,0.530159,0.0

In [17]:
y=df[['Type']]
y

     Type
0       1
1       1
2       1
3       1
4       1
..    ...
209     7
210     7
211     7
212     7
213     7

[214 rows x 1 columns]

In [18]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=70)

In [19]:
#Default value for finding the impurity is Gini index
tree=DecisionTreeClassifier()

In [20]:
tree.fit(x_train,y_train)

DecisionTreeClassifier()

In [21]:
y_pred=tree.predict(x_test)

In [22]:
y_pred

array([7, 1, 6, 3, 1, 3, 1, 2, 1, 7, 6, 1, 1, 1, 2, 6, 1, 1, 1, 7, 1, 1,
       2, 3, 2, 3, 1, 1, 1, 1, 1, 1, 1, 5, 7, 1, 7, 3, 7, 3, 7, 5, 2])

In [23]:
accuracy_score(y_test,y_pred)

0.6511627906976745

In [24]:
confusion_matrix(y_test,y_pred)

array([[14,  0,  3,  0,  0,  1],
       [ 4,  4,  1,  1,  1,  0],
       [ 2,  1,  1,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  2,  0],
       [ 0,  0,  1,  0,  0,  6]])

In [25]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.70      0.78      0.74        18
           2       0.80      0.36      0.50        11
           3       0.17      0.25      0.20         4
           5       0.50      1.00      0.67         1
           6       0.67      1.00      0.80         2
           7       0.86      0.86      0.86         7

    accuracy                           0.65        43
   macro avg       0.62      0.71      0.63        43
weighted avg       0.70      0.65      0.65        43

In [26]:
Ri=float(input('Enter the refractive index of glass'))
NA=float(input('Enter the sodium content of glass'))
MG=float(input('Enter the magnesium content of glass'))
AL=float(input('Enter the aluminium content of glass'))
SI=float(input('Enter the silicon content of glass'))
k=float(input('Enter the potassium content of glass'))
CA=float(input('Enter the calcium content of glass'))
BA=float(input('Enter the barium content of glass'))
FE=float(input('Enter the iron content of glass'))
Type=tree.predict([[Ri,NA,MG,AL,SI,k,CA,BA,FE]])
if(Type==1):
    print("building_windows_float_processed")
elif(Type==2):
    print("building_windows_non_float_processed")
elif(Type==3):
    print(" vehicle_windows_float_processed")
elif(Type==4):
    print("vehicle_windows_non_float_processed")
elif(Type==5):
    print("containers")
elif(Type==6):
    print("tableware")
elif(Type==7):
    print("headlamps")
else:
    print("Different Glass Type")

Enter the refractive index of glass

ValueError: could not convert string to float: ''